---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-java-app
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: myapp
        image: "ramichlagou/web-java-app:1.0.0"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-java-app
  namespace: default
spec:
  selector:
    app: java-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 82